# Generated by Django 4.2.27 on 2026-01-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0003_galleryimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_display', models.CharField(blank=True, help_text='Human-readable phone number', max_length=64)),
                ('phone_link', models.CharField(blank=True, help_text='tel:+... number', max_length=64)),
                ('address_display', models.TextField(blank=True, help_text='Address to show on the contact page')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Contact information',
                'verbose_name_plural': 'Contact information',
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('periods', models.TextField(blank=True, help_text='One period per line, e.g. "10 am–1 pm"')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='dentist_app.contactinfo')),
            ],
            options={
                'verbose_name': 'Opening hour',
                'verbose_name_plural': 'Opening hours',
                'ordering': ['order'],
            },
        ),
    ]
