# Generated by Django 4.2.27 on 2026-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0004_contactinfo_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='what_is',
            field=models.TextField(blank=True, help_text='What it is (displayed under the "What it is" label)'),
        ),
        migrations.AddField(
            model_name='service',
            name='when_to_do',
            field=models.TextField(blank=True, help_text='When to do it (displayed under the label)'),
        ),
        migrations.AddField(
            model_name='service',
            name='why_necessary',
            field=models.TextField(blank=True, help_text="Why it's necessary (displayed under the label)"),
        ),
    ]
