# Generated by Django 4.2.27 on 2026-01-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the certification or qualification', max_length=200)),
                ('image', models.ImageField(help_text='Upload certification image, logo, or badge', upload_to='certifications/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order'],
            },
        ),
    ]
